### ISSUE TITLE
not find

### ISSUE THREAD

**Issue by csy7749** [NullTale/VolFx#1]
![image](https://github.com/NullTale/VolFx/assets/44502734/a4a7c5fc-52a1-482c-9300-93be2f9ae641)

**Comment by NullTale** [comment]
Apologize, didn't expect the attention "making the repository public breaks all the media in the Readme", wanted to test and fix everything today.
 * so you can't finalize it with git until you publish it...

**Comment by csy7749** [comment]
Thanks，I really like your work！

**Comment by NullTale** [comment]
Thank you more, very nice to hear!
