### ISSUE TITLE
I can't add any effect

### ISSUE THREAD

**Issue by Mejval5** [NullTale/VolFx#2]
I tried adding all of them, and all of them are returning the same thing.
Add All Unique doesn't work either.

![image](https://github.com/NullTale/VolFx/assets/48858230/a36e168b-bc10-46c9-9ca9-de82bfb926bf)
![image](https://github.com/NullTale/VolFx/assets/48858230/ccd8f692-2932-487d-b044-f26d357573a4)

**Comment by NullTale** [comment]
What version of unity?

**Comment by Mejval5** [comment]
Seems like the issue is `AssetDatabase.SaveAssets();`

![image](https://github.com/NullTale/VolFx/assets/48858230/64669c71-ee36-4402-a9da-aaad11a8bce0)

When it is triggered it disposes the propertyList

This fixes it.
![image](https://github.com/NullTale/VolFx/assets/48858230/9e423f06-c0ac-46b5-b4ef-0b4f518d73df)

**Comment by Mejval5** [comment]
I wanted to add a new branch and open a PR, but no permissions :(

**Comment by Mejval5** [comment]
> What version of unity?

2022.3.15f1

**Comment by Mejval5** [comment]
There is similar issue when removing items from the collection

![image](https://github.com/NullTale/VolFx/assets/48858230/064f44b3-006f-4a38-9cfe-f9570c84623d)

**Comment by Mejval5** [comment]
Fortunatelly you can remove the feature twice to fix that. First time it break and second time it is finally removed.

**Comment by Mejval5** [comment]
First time broken, second time removed
![image](https://github.com/NullTale/VolFx/assets/48858230/cd46ab9b-af4d-4319-9425-b42fba2450ea)
![image](https://github.com/NullTale/VolFx/assets/48858230/ec3678e6-8f40-46b7-9560-ec3f6955ffc1)

Throwing that exception two comments above https://github.com/NullTale/VolFx/issues/2#issuecomment-1890966093

**Comment by NullTale** [comment]
ok thx, Ill check it
* SaveAssets is a wokraround to apply changes, it seems they changed something in the new versions

**Comment by Mejval5** [comment]
![image](https://github.com/NullTale/VolFx/assets/48858230/77b3f41b-f535-4d77-9125-771ea0e17232)
This one is the cause when removing items.

It could maybe be also because I am using the Asset refresh method Directory Monitoring, Hot Reload for Unity, or other reasons.
![image](https://github.com/NullTale/VolFx/assets/48858230/f8264840-2f1d-496c-aeea-75fd638c0dd3)

**Comment by Mejval5** [comment]
I am also using XR package. Doubt it changes anything though...

**Comment by NullTale** [comment]
Well, it's really because of SaveAssets call, fixed by removing with the define for a new versions~ 
on the test, it seems to be working.. thx!

**Comment by Mejval5** [comment]
Epic, thanks!
