### ISSUE TITLE
Add warning to Depth mode when depth map is not generated

### ISSUE THREAD

**Issue by Mejval5** [NullTale/VolFx#3]
Would be nice to have warning when the depth mode is used that you need to generate depth map in the URP settings
![image](https://github.com/NullTale/VolFx/assets/48858230/dee813a3-e9f6-4a0c-b23d-649897061516)

Cause without that the outline just doesn't work in the outline mode
![image](https://github.com/NullTale/VolFx/assets/48858230/54beb8a2-fb7c-41a2-bef8-ea2721ae33d5)

**Comment by NullTale** [comment]
thx, that would be really nice, but it's an outline related issue https://github.com/NullTale/OutlineFilter
* added a description for now

**Comment by Mejval5** [comment]
my bad, will reopen one there
