### ISSUE TITLE
No license specified in the project source

### ISSUE THREAD

**Issue by adamski11** [NullTale/VolFx#4]
Whilst I spotted you said this was under MIT license on your Reddit post, really there needs to be a clear and obvious license available to clear the project for use.  If you are happy using MIT as you have already stated, if you can add in the details to this template and add it to the root of the project, that will be automatically picked up by GitHub and will help clarify license of the project for us all

[LICENSE.MD](https://github.com/NullTale/VolFx/files/13937460/LICENSE.MD)

**Comment by NullTale** [comment]
✓
